In [6]:
import snf
digits = snf.datasets.load_digits()
digits.data

[array([[0.06588, 0.19731, 0.10383, ..., 0.39437, 0.04997, 0.34487],
        [0.04914, 0.17597, 0.10551, ..., 0.44528, 0.08398, 0.35409],
        [0.03417, 0.22765, 0.10877, ..., 0.44503, 0.07123, 0.26146],
        ...,
        [0.20397, 0.63796, 0.2894 , ..., 0.44367, 0.26406, 0.51523],
        [0.14686, 0.50432, 0.31241, ..., 0.44339, 0.07831, 0.43733],
        [0.19815, 0.4815 , 0.45344, ..., 0.42721, 0.13237, 0.30224]]),
 array([[0., 3., 4., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 2., 1., 0.],
        ...,
        [0., 1., 3., ..., 4., 4., 2.],
        [0., 0., 3., ..., 4., 4., 3.],
        [0., 0., 1., ..., 0., 0., 0.]]),
 array([[ 98., 236., 531., ...,  15.,  12.,  13.],
        [121., 193., 607., ...,  13.,  15.,  11.],
        [115., 141., 590., ...,  14.,  13.,   6.],
        ...,
        [265., 537., 776., ...,   7.,  11.,  17.],
        [261., 387., 712., ...,  12.,  12.,  17.],
        [315., 449., 734., ...,  12.,  10.,  13.]]),
 

In [28]:
len(digits.data[0])

600

In [33]:
affinity_networks = snf.make_affinity(digits.data, metric='euclidean')
fused_network = snf.snf(affinity_networks)

In [10]:
fused_network.shape

(600, 600)

In [18]:
import numpy as np

def check_symmetric(a, rtol=1e-05, atol=1e-08):
    return np.allclose(a, a.T, rtol=rtol, atol=atol)

check_symmetric(fused_network)

True

In [15]:
numpy.fill_diagonal(fused_network, 1)

In [16]:
fused_network

array([[1.00000000e+00, 4.45961825e-03, 4.31131465e-03, ...,
        1.30417738e-04, 1.11812794e-04, 1.71489830e-04],
       [4.45961825e-03, 1.00000000e+00, 5.18360724e-03, ...,
        1.33297048e-04, 1.12474158e-04, 1.79473577e-04],
       [4.31131465e-03, 5.18360724e-03, 1.00000000e+00, ...,
        1.28992762e-04, 1.07519663e-04, 1.77492231e-04],
       ...,
       [1.30417738e-04, 1.33297048e-04, 1.28992762e-04, ...,
        1.00000000e+00, 2.92642775e-03, 3.29185955e-03],
       [1.11812794e-04, 1.12474158e-04, 1.07519663e-04, ...,
        2.92642775e-03, 1.00000000e+00, 3.60456328e-03],
       [1.71489830e-04, 1.79473577e-04, 1.77492231e-04, ...,
        3.29185955e-03, 3.60456328e-03, 1.00000000e+00]])

In [ ]:
x= fused_network.flatten()

In [46]:
np.sum(x > 0.001)

181156

In [50]:
from sklearn.cluster import spectral_clustering
from sklearn.metrics import v_measure_score

labels = spectral_clustering(fused_network, n_clusters=4)

In [51]:
labels

array([0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 3, 2, 3, 3, 2, 3, 2, 2, 2, 3, 3, 3, 2, 3, 2, 2, 3, 3, 2,
       2, 2, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2,
       3, 2, 3, 2, 3, 3, 2, 2, 2, 2, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3, 2, 3,
       2, 3, 2, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 2, 3, 3, 2, 3, 3, 2, 2, 3, 3, 2, 2, 3, 3,

In [ ]:
}